-- Run this script in the Supabase SQL Editor

-- 1. Create users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create supplier table
CREATE TABLE supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    kontak TEXT,
    alamat TEXT,
    keterangan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create barang table
CREATE TABLE barang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_barang TEXT UNIQUE NOT NULL,
    nama_barang TEXT NOT NULL,
    merk TEXT,
    kategori TEXT,
    stok INTEGER DEFAULT 0,
    harga_beli NUMERIC DEFAULT 0,
    harga_jual NUMERIC DEFAULT 0,
    satuan TEXT DEFAULT 'Unit',
    keterangan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create transaksi_masuk table
CREATE TABLE transaksi_masuk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    barang_id BIGINT REFERENCES barang(id) ON DELETE CASCADE,
    supplier_id BIGINT REFERENCES supplier(id) ON DELETE SET NULL,
    jumlah INTEGER NOT NULL,
    harga_satuan NUMERIC NOT NULL,
    total_harga NUMERIC NOT NULL,
    keterangan TEXT,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Create transaksi_keluar table
CREATE TABLE transaksi_keluar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    barang_id BIGINT REFERENCES barang(id) ON DELETE CASCADE,
    jumlah INTEGER NOT NULL,
    tujuan TEXT,
    keterangan TEXT,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default admin user
-- Password is 'admin123'
INSERT INTO users (username, password, full_name, role) 
VALUES ('admin', '$2b$10$wFvzsCCLKNDUG5F1UaatkecQ.AL3zzQxRHCMatCfKJOmbjbnjKAS2', 'Administrator', 'admin');
